apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nid7ol7vk-nodejs 
  janus-idp.io/tekton: nid7ol7vk-nodejs
  backstage.io/kubernetes-id: nid7ol7vk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nid7ol7vk-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml