apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nid7ol7vk-nodejs
  janus-idp.io/tekton: nid7ol7vk-nodejs
  backstage.io/kubernetes-id: nid7ol7vk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nid7ol7vk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
