apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nid7ol7vk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nid7ol7vk-nodejs 
  name: nid7ol7vk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nid7ol7vk-nodejs 
